PythonGames/PythonGames/Areas/Gerenciamento/Controllers/SuporteController.cs
using PythonGames.Classes.DAOs;
using PythonGames.Classes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PythonGames.Areas.Gerenciamento.Controllers
{
    public class SuporteController : Controller
    {
        CarrinhoDAO carDAO = new CarrinhoDAO();
        ItensCarrinhoDAO icDAO = new ItensCarrinhoDAO();
        SuporteDAO supDAO = new SuporteDAO();
        // GET: Gerenciamento/Suporte
        public ActionResult Index()
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            return View(supDAO.Listar());
        }

        [HttpPost]
        public ActionResult Index(string cpf_cli)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            if (cpf_cli == "")
                cpf_cli = "___.___.___-__";
            return View(supDAO.ListarPorCpf(cpf_cli));
        }



        public ActionResult EscolherCarrinho()
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            return View(carDAO.Listar());
        }

        [HttpPost]
        public ActionResult EscolherCarrinho(string cpf_cli)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            if (cpf_cli == "")
                cpf_cli = "___.___.___-__";
            return View(carDAO.ListarPorCpf(cpf_cli));
        }



        public ActionResult VendaEscolhida(int cd)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            return View(icDAO.Listar(cd));
        }



        public ActionResult Cadastrar(int cd_produto, int cd_carrinho)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            Suporte suporte = new Suporte()
            {
                cd_carrinho = cd_carrinho,
                cd_produto = cd_produto
            };

            return View(suporte);
        }

        [HttpPost]
        public ActionResult Cadastrar(Suporte sup)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    supDAO.Insert(sup);
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.ErroMsg = "Algo Deu Errado :(";
                    return View();
                }
            }
            else
                return View();
        }



        public ActionResult Detalhes(int cd)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            Suporte sup = supDAO.ListarPorCd(cd);
            ViewBag.Cd = cd;
            ViewBag.Status = sup.sup_status;

            return View(sup);
        }



        public ActionResult AlterarStatus(int cd)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            supDAO.UpdateStatus(cd);
            return RedirectToAction("Detalhes", new { cd = cd });
        }



        public ActionResult Alterar(int cd)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            if((int)Session["AcFuncionarioLogado"] != 1)
                return RedirectToAction("Index");

            Suporte sup = supDAO.ListarPorCd(cd);
            ViewBag.Cd = cd;

            return View(sup);
        }

        [HttpPost]
        public ActionResult Alterar(Suporte sup)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    supDAO.Update(sup);
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.ErroMsg = "Algo Deu Errado :(";
                    return View();
                }
            }
            else
            {
                return View();
            }
        }



        public ActionResult Deletar(int cd)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            if ((int)Session["AcFuncionarioLogado"] != 1)
                return RedirectToAction("Index");

            supDAO.Delete(cd);

            return RedirectToAction("Index");
        }
    }
}

PythonGames/PythonGames/Controllers/UsuarioController.cs
using PythonGames.Classes;
using PythonGames.Classes.DAOs;
using PythonGames.Classes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PythonGames.Controllers
{
    public class UsuarioController : Controller
    {
        CarrinhoDAO carDAO = new CarrinhoDAO();
        ClienteDAO cliDAO = new ClienteDAO();
        EntregaDAO entDAO = new EntregaDAO();
        ItensCarrinhoDAO icDAO = new ItensCarrinhoDAO();
        ProdutoDAO prodDAO = new ProdutoDAO();
        SuporteDAO supDAO = new SuporteDAO();
        TesteDeGameDAO testeDAO = new TesteDeGameDAO();

        // GET: Usuario

        // Página de Alterar dados
        public ActionResult Index()
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index","Home");

            int cd = (int)Session["CdClienteLogado"];

            return View(cliDAO.ListarPorCd(cd));
        }

        [HttpPost]
        public ActionResult Index(Cliente cliente)
        {
            Cliente antCli = cliDAO.ListarPorCd(cliente.cd_cliente);
            if (ModelState.IsValid)
            {
                if (antCli.cpf_cli == cliente.cpf_cli || cliDAO.ChecaCPF(cliente.cpf_cli))
                {
                    if (antCli.cpf_cli == cliente.cpf_cli || Validacoes.ValidaCPF(cliente.cpf_cli))
                    {
                        if (antCli.nm_email == cliente.nm_email || cliDAO.ChecaEmail(cliente.nm_email))
                        {
                            try
                            {
                                cliDAO.Update(cliente);
                                return RedirectToAction("Index");
                            }
                            catch
                            {
                                ViewBag.ErroMsg = "Algo deu Errado );";
                                return View();
                            }
                        }
                        else
                        {
                            ViewBag.ErroMsg = "Este Email já está registrado!";
                            return View();
                        }
                    }
                    else
                    {
                        ViewBag.ErroMsg = "CPF Inválido!";
                        return View();
                    }

                }
                else
                {
                    ViewBag.ErroMsg = "Este CPF já está registrado!";
                    return View();
                }
            }
            else
                return View();
        }



        // Lista de compras
        public ActionResult Compras()
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            int cd = (int)Session["CdClienteLogado"];

            return View(carDAO.ListarPorCliente(cd));
        }

        public ActionResult ItensCompra(int cd)
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            return View(icDAO.Listar(cd));
        }



        public ActionResult DadosEntrega(int cd)
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            Entrega ent = entDAO.ListarPorCd(cd);
            ViewBag.Complemento = ent.nm_complemento;

            return View(ent);
        }



        // Suporte
        public ActionResult Suporte(int cd_carrinho, int cd_produto)
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            Suporte sup = new Suporte();
            sup.cd_carrinho = cd_carrinho;
            sup.cd_produto = cd_produto;

            return View(sup);
        }

        [HttpPost]
        public ActionResult Suporte(Suporte sup)
        {
            sup.dt_sup = DateTime.Now;
            if (ModelState.IsValid)
            {
                try
                {
                    supDAO.Insert(sup);
                    return RedirectToAction("ListaSuportes");
                }
                catch
                {
                    ViewBag.ErroMsg = "Algo Deu Errado :(";
                    return View();
                }
            }
            else
                return View();
        }

        public ActionResult ListaSuportes()
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            string cpf = (string)Session["CpfClienteLogado"];
            return View(supDAO.ListarPorCliente(cpf));
        }

        public ActionResult DetalhesSuporte(int cd)
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            Suporte sup = supDAO.ListarPorCd(cd);

            ViewBag.Cd = cd;
            ViewBag.Status = sup.sup_status;

            return View(sup);
        }

        public ActionResult DeletarSuporte(int cd)
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            supDAO.Delete(cd);

            return RedirectToAction("ListaSuportes");
        }



        // Teste De Game
        public ActionResult ListaDeTestes()
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            int cd = (int)Session["CdClienteLogado"];

            return View(testeDAO.ListarPorCliente(cd));
        }

        public ActionResult EscolherGame()
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            return View(prodDAO.ListarPorCategoria("Games"));
        }

        public ActionResult CadastrarTeste(int cd)
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            TesteDeGame teste = new TesteDeGame();
            teste.cd_produto = cd;
            teste.cd_cliente = (int)Session["CdClienteLogado"];

            return View(teste);
        }

        [HttpPost]
        public ActionResult CadastrarTeste(TesteDeGame teste)
        {
            if (ModelState.IsValid)
            {
                if (testeDAO.ChecaDisp(teste) && teste.dt_teste > DateTime.Now)
                {
                    try
                    {
                        testeDAO.Insert(teste);
                        return RedirectToAction("ListaDeTestes");
                    }
                    catch
                    {
                        ViewBag.ErroMsg = "Algo deu Errado );";
                        return View();
                    }
                }
                else
                {
                    ViewBag.ErroMsg = "Horário indisponível!";
                    return View();
                }
            }
            else
                return View();
        }

        public ActionResult CancelarTeste(int cd)
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            testeDAO.Delete(cd);

            return RedirectToAction("ListaDeTestes");
        }
    }
}

PythonGames/PythonGames/Views/Usuario/CadastrarTeste.cshtml
@model PythonGames.Classes.Models.TesteDeGame

@{
    ViewBag.Title = "Teste De Game";
}

<h2 class="titulo-form">Finalize o Agendamento</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div style="display: none;">
            <div class="">
                @Html.LabelFor(model => model.cd_produto, htmlAttributes: new { @class = "" })
                <div class="">
                    @Html.EditorFor(model => model.cd_produto, new { htmlAttributes = new { @class = "" } })
                    @Html.ValidationMessageFor(model => model.cd_produto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="">
                @Html.LabelFor(model => model.cd_cliente, htmlAttributes: new { @class = "" })
                <div class="">
                    @Html.EditorFor(model => model.cd_cliente, new { htmlAttributes = new { @class = "" } })
                    @Html.ValidationMessageFor(model => model.cd_cliente, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="div-form-col1">
            <div class="">
                @Html.LabelFor(model => model.dt_teste, htmlAttributes: new { @class = "" })
                <div class="">
                    @Html.EditorFor(model => model.dt_teste, new { htmlAttributes = new { @class = "", @type = "date" } })
                    @Html.ValidationMessageFor(model => model.dt_teste, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="div-form-col2">
            <div class="">
                @Html.LabelFor(model => model.hr_teste, htmlAttributes: new { @class = "" })
                <div class="">
                    @Html.DropDownListFor(model => model.hr_teste,
                      new List<SelectListItem> {
                      new SelectListItem{ Value = "08:00" , Text = "08:00"  },
                      new SelectListItem{ Value = "08:30" , Text = "08:30"  },
                      new SelectListItem{ Value = "09:00" , Text = "09:00"  },
                      new SelectListItem{ Value = "09:30" , Text = "09:30"  },
                      new SelectListItem{ Value = "10:00" , Text = "10:00"  },
                      new SelectListItem{ Value = "10:30" , Text = "10:30"  },
                      new SelectListItem{ Value = "11:00" , Text = "11:00"  },
                      new SelectListItem{ Value = "11:30" , Text = "11:30"  },
                      new SelectListItem{ Value = "12:00" , Text = "12:00"  },
                      new SelectListItem{ Value = "12:30" , Text = "12:30"  },
                      new SelectListItem{ Value = "13:00" , Text = "13:00"  },
                      new SelectListItem{ Value = "13:30" , Text = "13:30"  },
                      new SelectListItem{ Value = "14:00" , Text = "14:00"  },
                      new SelectListItem{ Value = "14:30" , Text = "14:30"  },
                      new SelectListItem{ Value = "15:00" , Text = "15:00"  },
                      new SelectListItem{ Value = "15:30" , Text = "15:30"  },
                      new SelectListItem{ Value = "16:00" , Text = "16:00"  },
                      new SelectListItem{ Value = "16:30" , Text = "16:30"  },
                      new SelectListItem{ Value = "17:00" , Text = "17:00"  },
                      new SelectListItem{ Value = "17:30" , Text = "17:30"  }
                    }, new { @id = "", onclick = "" })
                    @Html.ValidationMessageFor(model => model.hr_teste, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>



        <div class="">
            <div class="btn-form">
                <p class="text-danger">
                    @ViewBag.ErroMsg
                </p>
                <input type="submit" value="Agendar" class="btn btn-orange" />
            </div>
        </div>
    </div>
}
<br />
<hr />
<div class="link-voltar-form text-center">
    <i class="fas fa-arrow-circle-left" onclick="history.back()" style="cursor: pointer;">
        Voltar
    </i>
    @Html.ActionLink(" Meus Dados", "Index", null, new { @class = "fas fa-user" })
    &nbsp;
    @Html.ActionLink(" Minhas Compras", "Compras", null, new { @class = "fas fa-shopping-bag" })
    &nbsp;
    @Html.ActionLink(" Testes De Games", "ListaDeTestes", null, new { @class = "fas fa-gamepad" })
    &nbsp;
    @Html.ActionLink(" Suportes", "ListaSuportes", null, new { @class = "fas fa-wrench" })
</div>

PythonGames/PythonGames/Views/Usuario/Compras.cshtml
@model IEnumerable<PythonGames.Classes.Models.Carrinho>

@{
    ViewBag.Title = "Minhas Compras";
}

<h2 class="titulo-form">Minhas Compras</h2>
<br>
<div class="compras-list">
    @foreach (var item in Model)
    {

        <div class="card card-compra text-center">
            <div class="card-body">
                <h5 class="card-title">
                    @Html.DisplayNameFor(model => model.dt_venda): @Html.DisplayFor(modelItem => item.dt_venda)
                </h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">@Html.DisplayNameFor(model => model.cd_carrinho): @Html.DisplayFor(modelItem => item.cd_carrinho)</li>
                <li class="list-group-item">@Html.DisplayNameFor(model => model.vl_total): @Html.DisplayFor(modelItem => item.vl_total) R$</li>
                <li class="list-group-item">@Html.DisplayNameFor(model => model.nm_forma): <br />@Html.DisplayFor(modelItem => item.nm_forma)</li>
            </ul>
            <div class="card-body">
                @Html.ActionLink("Ver Itens", "ItensCompra", new { cd = item.cd_carrinho })
                @if (item.cd_forma == 1 || item.cd_forma == 2)
                {
                    <span>|</span>
                    @Html.ActionLink("Dados de entrega", "DadosEntrega", new { cd = item.cd_carrinho })
                }
            </div>
        </div>

    }

</div>
<br />
<hr />
<div class="link-voltar-form text-center">
    <i class="fas fa-arrow-circle-left" onclick="history.back()" style="cursor: pointer;">
        Voltar
    </i>
    @Html.ActionLink(" Meus Dados", "Index", null, new { @class = "fas fa-user" })
    &nbsp;
    @Html.ActionLink(" Minhas Compras", "Compras", null, new { @class = "fas fa-shopping-bag" })
    &nbsp;
    @Html.ActionLink(" Testes De Games", "ListaDeTestes", null, new { @class = "fas fa-gamepad" })
    &nbsp;
    @Html.ActionLink(" Suportes", "ListaSuportes", null, new { @class = "fas fa-wrench" })
</div>

PythonGames/PythonGames/Views/Usuario/DadosEntrega.cshtml
@model PythonGames.Classes.Models.Entrega

@{
    ViewBag.Title = "Dados da Entrega";
}

<h2 class="titulo-form">Dados da Entrega</h2>

<div>
    <hr />
    <div class="div-form-col1">
        <b>
            @Html.DisplayNameFor(model => model.cd_carrinho)
        </b>

        <p>
            @Html.DisplayFor(model => model.cd_carrinho)
        </p>

        <b>
            @Html.DisplayNameFor(model => model.dt_entrega)
        </b>

        <p>
            @Html.DisplayFor(model => model.dt_entrega)
        </p>

        <b>
            @Html.DisplayNameFor(model => model.vl_frete)
        </b>

        <p>
            @Html.DisplayFor(model => model.vl_frete)
        </p>

        <b>
            @Html.DisplayNameFor(model => model.no_cep)
        </b>

        <p>
            @Html.DisplayFor(model => model.no_cep)
        </p>

        <b>
            @Html.DisplayNameFor(model => model.nm_estado)
        </b>

        <p>
            @Html.DisplayFor(model => model.nm_estado)
        </p>
    </div>
    <div class="div-form-col2">
        <b>
            @Html.DisplayNameFor(model => model.nm_cidade)
        </b>

        <p>
            @Html.DisplayFor(model => model.nm_cidade)
        </p>

        <b>
            @Html.DisplayNameFor(model => model.nm_bairro)
        </b>

        <p>
            @Html.DisplayFor(model => model.nm_bairro)
        </p>

        <b>
            @Html.DisplayNameFor(model => model.nm_rua)
        </b>

        <p>
            @Html.DisplayFor(model => model.nm_rua)
        </p>

        <b>
            @Html.DisplayNameFor(model => model.no_end)
        </b>

        <p>
            @Html.DisplayFor(model => model.no_end)
        </p>
        @if (ViewBag.Complemento != "")
        {
            <b>
                @Html.DisplayNameFor(model => model.nm_complemento)
            </b>

            <p>
                @Html.DisplayFor(model => model.nm_complemento)
            </p>
        }


    </div>
</div>
<br />
<hr />
<div class="link-voltar-form text-center">
    <i class="fas fa-arrow-circle-left" onclick="history.back()" style="cursor: pointer;">
        Voltar
    </i>
    @Html.ActionLink(" Meus Dados", "Index", null, new { @class = "fas fa-user" })
    &nbsp;
    @Html.ActionLink(" Minhas Compras", "Compras", null, new { @class = "fas fa-shopping-bag" })
    &nbsp;
    @Html.ActionLink(" Testes De Games", "ListaDeTestes", null, new { @class = "fas fa-gamepad" })
    &nbsp;
    @Html.ActionLink(" Suportes", "ListaSuportes", null, new { @class = "fas fa-wrench" })
</div>

PythonGames/PythonGames/Views/Usuario/DetalhesSuporte.cshtml
@model PythonGames.Classes.Models.Suporte
@{
    ViewBag.Title = "Detalhes de Suporte";
}

<h2 class="titulo-form">Detalhes de Suporte</h2>
<br />
<div>
    <div class="form-carrinho">

        <div class="item-form-carrinho form-carrinho-img" style="background-image: url('@Html.DisplayFor(model => model.link_img)');">
        </div>
        <div class="item-form-carrinho form-carrinho-inputs">
            <h3>@Html.DisplayFor(model => model.nm_prod)</h3>
            <hr style="border: 1px solid rgb(255, 127, 38);">

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.cd_carrinho)
                </span>
                @Html.DisplayFor(model => model.cd_carrinho)
            </p>

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.dt_sup)
                </span>
                @Html.DisplayFor(model => model.dt_sup)
            </p>

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.sup_descricao)
                </span>
                @Html.DisplayFor(model => model.sup_descricao)
            </p>

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.sup_status)
                </span>
                @if (@ViewBag.Status == 0)
                {
                    <span class="text-danger fas fa-times-circle">
                        Não Atendido
                    </span>
                }
                else
                {
                    <span class="fas fa-check-circle text-success" title="Cheque seu Email!!">
                        Atendido
                    </span>
                }
            </p>

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.cpf_cli)
                </span>
                @Html.DisplayFor(model => model.cpf_cli)
            </p>

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.nm_cli)
                </span>
                @Html.DisplayFor(model => model.nm_cli)
            </p>

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.nm_email)
                </span>
                @Html.DisplayFor(model => model.nm_email)
            </p>

            <br />
            @Html.ActionLink("Cancelar", "DeletarSuporte", new { cd = @ViewBag.Cd }, new
            {
                @class = "btn-del",
                onclick = "return confirm('Deseja realmente cancelar este suporte?? ');"
            })

        </div>
    </div>
</div>
<br />
<hr />
<div class="link-voltar-form text-center">
    <i class="fas fa-arrow-circle-left" onclick="history.back()" style="cursor: pointer;">
        Voltar
    </i>
    @Html.ActionLink(" Meus Dados", "Index", null, new { @class = "fas fa-user" })
    &nbsp;
    @Html.ActionLink(" Minhas Compras", "Compras", null, new { @class = "fas fa-shopping-bag" })
    &nbsp;
    @Html.ActionLink(" Testes De Games", "ListaDeTestes", null, new { @class = "fas fa-gamepad" })
    &nbsp;
    @Html.ActionLink(" Suportes", "ListaSuportes", null, new { @class = "fas fa-wrench" })
</div>

PythonGames/PythonGames/Views/Usuario/EscolherGame.cshtml
@model IEnumerable<PythonGames.Classes.Models.Produto>
<link href="~/Content/EstiloProdutos.css" rel="stylesheet" />
@{
    ViewBag.Title = "Escolher Game";
}

<h2 class="titulo-form">Escolha o Game!</h2>


<ul class="prod-group">

    @foreach (var item in Model)
    {
        <li>

            <div class="card-prod">
                <div class="img-prod" style="background-image: url('@Html.DisplayFor(modelItem => item.link_img)');">
                </div>
                <h5 title="@Html.DisplayFor(modelItem => item.nm_prod)">
                    @Html.DisplayFor(modelItem => item.nm_prod)
                </h5>
                <p>@Html.DisplayFor(modelItem => item.nm_categoria)</p>
                <p>R$ @Html.DisplayFor(modelItem => item.vl_prod)</p>
                <p>Em estoque: @Html.DisplayFor(modelItem => item.qt_estoque)</p>

                <br />

            </div>
            <div class="add-link">
                @Html.ActionLink("+", "CadastrarTeste", new { cd = item.cd_produto })
            </div>



        </li>
    }

</ul>
<br />
<hr />
<div class="link-voltar-form text-center">
    <i class="fas fa-arrow-circle-left" onclick="history.back()" style="cursor: pointer;">
        Voltar
    </i>
    @Html.ActionLink(" Meus Dados", "Index", null, new { @class = "fas fa-user" })
    &nbsp;
    @Html.ActionLink(" Minhas Compras", "Compras", null, new { @class = "fas fa-shopping-bag" })
    &nbsp;
    @Html.ActionLink(" Testes De Games", "ListaDeTestes", null, new { @class = "fas fa-gamepad" })
    &nbsp;
    @Html.ActionLink(" Suportes", "ListaSuportes", null, new { @class = "fas fa-wrench" })
</div>

PythonGames/PythonGames/Views/Usuario/ItensCompra.cshtml
@model IEnumerable<PythonGames.Classes.Models.ItensCarrinho>
<link href="~/Content/EstiloProdutos.css" rel="stylesheet" />

@{
    ViewBag.Title = "Itens da vVenda";
}

<h2>Itens da Venda</h2>
<br />
<ul class="prod-group">

    @foreach (var item in Model)
    {
        <li>
            <div class="card-prod">
                <div class="img-prod" style="background-image: url('@Html.DisplayFor(modelItem => item.link_img)');">
                </div>
                <h5 title="@Html.DisplayFor(modelItem => item.nm_prod)">
                    @Html.DisplayFor(modelItem => item.nm_prod)
                </h5>
                <p>@Html.DisplayFor(modelItem => item.nm_categoria)</p>
                <p>Valor unitário: R$ @Html.DisplayFor(modelItem => item.vl_prod)</p>
                <p>Quantidade: @Html.DisplayFor(modelItem => item.qt_item)</p>
                <p>Valor total: R$ @Html.DisplayFor(modelItem => item.vl_item)</p>
                <br />
                @Html.ActionLink("Solicitar Suporte","Suporte", new { cd_carrinho = item.cd_carrinho, cd_produto = item.cd_produto }, new { @class = "btn-del" } )
            </div>
        </li>

    }

</ul>
<br />
<hr />
<div class="link-voltar-form text-center">
    <i class="fas fa-arrow-circle-left" onclick="history.back()" style="cursor: pointer;">
        Voltar
    </i>
    @Html.ActionLink(" Meus Dados", "Index", null, new { @class = "fas fa-user" })
    &nbsp;
    @Html.ActionLink(" Minhas Compras", "Compras", null, new { @class = "fas fa-shopping-bag" })
    &nbsp;
    @Html.ActionLink(" Testes De Games", "ListaDeTestes", null, new { @class = "fas fa-gamepad" })
    &nbsp;
    @Html.ActionLink(" Suportes", "ListaSuportes", null, new { @class = "fas fa-wrench" })
</div>