PythonGames/PythonGames/Controllers/CarrinhoController.cs
using PythonGames.Classes;
using PythonGames.Classes.DAOs;
using PythonGames.Classes.Models;
using PythonGames.ServiceReferenceCorreios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PythonGames.Controllers
{
    public class CarrinhoController : Controller
    {
        CarrinhoDAO carDAO = new CarrinhoDAO();
        CartaoDAO cartaoDAO = new CartaoDAO();
        EntregaDAO entDAO = new EntregaDAO();
        FormaDePagamentoDAO frmDAO = new FormaDePagamentoDAO();
        ItensCarrinhoDAO icDAO = new ItensCarrinhoDAO();
        ProdutoDAO prodDAO = new ProdutoDAO();
        // GET: Carrinho
        public ActionResult Index()
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            Carrinho carrinho = (Carrinho)Session["CarrinhoCliente"];
            if (carrinho == null)
            {
                carrinho = new Carrinho();
                carrinho.cd_cliente = (int)Session["CdClienteLogado"];
                Session["CarrinhoCliente"] = carrinho;
            }
            ViewBag.ValorCarrinho = carrinho.vl_total;

            List<ItensCarrinho> lista = (List<ItensCarrinho>)Session["ItensCarrinhoCliente"];
            if (lista == null)
            {
                lista = new List<ItensCarrinho>();
                Session["ItensCarrinhoCliente"] = lista;
            }

            return View(lista);
        }



        public ActionResult AdicionarItem(int cd)
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });

            Produto prod = prodDAO.ListarPorCd(cd);
            ItensCarrinho item = new ItensCarrinho();

            item.cd_produto = prod.cd_produto;
            ViewBag.CdProduto = prod.cd_produto;
            ViewBag.NmProd = prod.nm_prod;
            ViewBag.LinkImg = prod.link_img;
            ViewBag.NmCat = prod.nm_categoria;
            ViewBag.VlProd = prod.vl_prod;
            ViewBag.QtEstoque = prod.qt_estoque;
            ViewBag.ProdDesc = prod.prod_desc;

            return View(item);
        }

        [HttpPost]
        public ActionResult AdicionarItem(ItensCarrinho item)
        {
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Login", "Home");

            if (item.qt_item > 0)
            {
                Carrinho carrinho = (Carrinho)Session["CarrinhoCliente"];
                if (carrinho == null)
                {
                    carrinho = new Carrinho();
                    carrinho.cd_cliente = (int)Session["CdClienteLogado"];
                    Session["CarrinhoCliente"] = carrinho;
                }
                ViewBag.ValorCarrinho = carrinho.vl_total;

                List<ItensCarrinho> lista = (List<ItensCarrinho>)Session["ItensCarrinhoCliente"];
                if (lista == null)
                {
                    lista = new List<ItensCarrinho>();
                    Session["ItensCarrinhoCliente"] = lista;
                }

                //deletando possivel existencia de outro item do mesmo produto
                var itemExclusao = lista.FirstOrDefault(i => i.cd_produto == item.cd_produto);
                lista.Remove(itemExclusao);

                Produto prod = prodDAO.ListarPorCd(item.cd_produto);

                item.cd_produto = prod.cd_produto;
                item.nm_prod = prod.nm_prod;
                item.link_img = prod.link_img;
                item.nm_categoria = prod.nm_categoria;
                item.vl_prod = prod.vl_prod;
                item.qt_estoque = prod.qt_estoque;
                item.prod_desc = prod.prod_desc;

                lista.Add(item);
                Session["ItensCarrinhoGerenciamento"] = lista;

                carrinho.vl_total = 0;
                foreach (ItensCarrinho ic in lista)
                {
                    carrinho.vl_total += ic.vl_item;
                }
                Session["CarrinhoGerenciamento"] = carrinho;

                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("AdicionarItem", new { cd = item.cd_produto });
        }



        public ActionResult RemoverItem(int cd)
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            Carrinho carrinho = (Carrinho)Session["CarrinhoCliente"];
            if (carrinho == null)
            {
                carrinho = new Carrinho();
                carrinho.cd_cliente = (int)Session["CdClienteLogado"];
                Session["CarrinhoCliente"] = carrinho;
            }

            List<ItensCarrinho> lista = (List<ItensCarrinho>)Session["ItensCarrinhoCliente"];
            if (lista == null)
            {
                lista = new List<ItensCarrinho>();
                Session["ItensCarrinhoCliente"] = lista;
            }

            var itemExclusao = lista.FirstOrDefault(i => i.cd_produto == cd);
            lista.Remove(itemExclusao);

            Session["ItensCarrinhoGerenciamento"] = lista;

            carrinho.vl_total = 0;
            foreach (ItensCarrinho ic in lista)
            {
                carrinho.vl_total += ic.vl_item;
            }
            Session["CarrinhoGerenciamento"] = carrinho;

            return RedirectToAction("Index");
        }



        public ActionResult ConfirmarCompra()
        {
            if (Session["FuncionarioLogado"] != null)
                return RedirectToAction("Index", "Funcionario", new { area = "Gerenciamento" });
            if (Session["ClienteLogado"] == null)
                return RedirectToAction("Index", "Home");

            Carrinho carrinho = (Carrinho)Session["CarrinhoCliente"];
            List<ItensCarrinho> lista = (List<ItensCarrinho>)Session["ItensCarrinhoCliente"];

            if (carrinho == null || lista == null || lista.Count == 0)
                return RedirectToAction("Index");

            ViewBag.Formas = frmDAO.ListarParaEcommerce();

            return View();
        }

        [HttpPost]
        public ActionResult ConfirmarCompra(Entrega entrega)
        {
            // Checando integridade do carrinho e dos itens do carrinho e checando se o carrinho não está vazio
            Carrinho carrinho = (Carrinho)Session["CarrinhoCliente"];
            List<ItensCarrinho> lista = (List<ItensCarrinho>)Session["ItensCarrinhoCliente"];
            if (carrinho == null || lista == null || lista.Count == 0)
            {
                ViewBag.ErroMsg = "Carrinho Vazio";
                ViewBag.Formas = frmDAO.ListarParaEcommerce();
                return View();
            }

            // Checando e passando valor do frete para o objeto entrega
            double dValorFrete;
            string sValorFrete = Request["vl_frete"];
            sValorFrete = sValorFrete.Replace("R$", string.Empty);
            //sValorFrete.Replace(",", ".");

            try
            {
                dValorFrete = Convert.ToDouble(sValorFrete);
                entrega.vl_frete = dValorFrete;
            }
            catch
            {
                ViewBag.ErroMsg = "Erro no cálculo do frete";
                ViewBag.Formas = frmDAO.ListarParaEcommerce();
                return View();
            }

            // Checando e passando o prazo de entrega e passando a data de previsão para o objeto entrega
            string sDtEntrega = Request["dt_entrega"];
            sDtEntrega = sDtEntrega.Replace(" dias", string.Empty);

            try
            {                
                entrega.dt_entrega = DateTime.Now.AddDays(int.Parse(sDtEntrega));
            }
            catch
            {
                ViewBag.ErroMsg = "Erro na Data de entrega";
                ViewBag.Formas = frmDAO.ListarParaEcommerce();
                return View();
            }

            // Passando código da forma para o carrinho
            int cdForma = int.Parse(Request["cd_forma"]);
            carrinho.cd_forma = cdForma;

            // Checando Dados do cartão e passando-os para um objeto
            string nm_cartao = Request["nm_cartao"];
            string no_cartao = Request["no_cartao"];
            string no_cvv = Request["no_cvv"];
            DateTime dt_validade = DateTime.Parse(Request["dt_validade"]);

            // Checando dados do cartão
            Cartao cartao = ChecaCartao(nm_cartao, no_cartao, no_cvv, dt_validade);
            if (cartao == null)
            {
                ViewBag.Formas = frmDAO.ListarParaEcommerce();
                return View();
            }

            //Inserindo dados no Banco e zerando Sessions
            carrinho.dt_venda = DateTime.Now;
            int cdIns = carDAO.InsertCliente(carrinho);
            foreach (ItensCarrinho item in lista)
            {
                item.cd_carrinho = cdIns;
                icDAO.Insert(item);
            }
            cartao.cd_carrinho = cdIns;
            cartaoDAO.Insert(cartao);
            entrega.cd_carrinho = cdIns;
            entDAO.Insert(entrega);
            Session["CarrinhoCliente"] = null;
            Session["ItensCarrinhoCliente"] = null;

            return RedirectToAction("Compras","Usuario");
        }



        public JsonResult CalculaFrete(string cep)
        {
            string cepArmazem = "06454911";

            CalcPrecoPrazoWSSoapClient wsCorreios = new CalcPrecoPrazoWSSoapClient();
            cResultado retornoCorreios = wsCorreios.CalcPrecoPrazo(

PythonGames/PythonGames/Views/Carrinho/AdicionarItem.cshtml
@model PythonGames.Classes.Models.ItensCarrinho

@{
    ViewBag.Title = "AdicionarItem";
}

<script>
    //recebendo dados do produto
    var valor = @ViewBag.VlProd;
    var estoque = @ViewBag.QtEstoque;

    function subQtd() {
        document.getElementById('input-qtd').value--;
        var i = document.getElementById('input-qtd').value;

        document.getElementById('input-valor').value = valor * i;

        if (i == 1)
            document.getElementById('btn-sub').disabled = true;

        document.getElementById('btn-sum').disabled = false;
    }

    function somaQtd() {
        document.getElementById('input-qtd').value++;
        document.getElementById('btn-sub').disabled = false;
        var i = document.getElementById('input-qtd').value;

        document.getElementById('input-valor').value = valor * i;

        if (i == estoque)
            document.getElementById('btn-sum').disabled = true;
    }

    function calcFrete(valor) {

        //Nova variável "cep" somente com dígitos.
        var cep = valor.replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {

            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{8}$/;

            //Valida o formato do CEP.
            if (validacep.test(cep)) {

                //Preenche os campos com "..." enquanto consulta webservice.
                frete(cep);
            }
            else {
                //cep é inválido.
                document.getElementById('txt_frete').style.display = "none";
                document.getElementById('resp_frete').value = ("");
            }
        } //fim if.
        else {
            //cep sem valor, limpa formulário.
            document.getElementById('txt_frete').style.display = "none";
            document.getElementById('resp_frete').value = ("");        }
    }

    function frete(cep) {
        $.ajax({
            url: '@Url.Action("CalculaFrete","Carrinho")?cep='+cep,
            type: "POST",
            contentType: "aplication/json",
            data: "",
            success: function (result) {
                document.getElementById('txt_frete').style.display = "block";
                document.getElementById('resp_frete').value = ("Prazo: "+result[0] + " dias  valor: "+result[1]+"R$");
            },
            error: function (xhr, exception) {
                document.getElementById('txt_frete').style.display = "none";
                document.getElementById('resp_frete').value = ("");
            }
        });
    }
</script>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div style="display: none;">
            <div class="form-group">
                @Html.LabelFor(model => model.cd_produto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.cd_produto, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.cd_produto, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>




        <div class="form-carrinho">

            <div class="item-form-carrinho form-carrinho-img" style="background-image: url('@ViewBag.LinkImg');">
            </div>
            <div class="item-form-carrinho form-carrinho-inputs">
                <h3>@ViewBag.NmProd</h3>
                <hr style="border: 1px solid rgb(255, 127, 38);">
                <h6>
                    @ViewBag.ProdDesc
                </h6>
                <p>
                    Categoria: @ViewBag.NmCat
                </p>


                @if (ViewBag.QtEstoque > 0)
                {
                    <p>
                        Valor total: @Html.EditorFor(model => model.vl_item, new { htmlAttributes = new { @style = "width: 50px;", @value = @ViewBag.VlProd, @id = "input-valor", @readonly = "readonly" } }) R$
                    </p>
                    <p>
                        Quantidade: &nbsp;
                        <input type="button" value="-" id="btn-sub" onclick="subQtd()" disabled />
                        @Html.EditorFor(model => model.qt_item, new { htmlAttributes = new { @class = "", @id = "input-qtd", @min = "1", @max = @ViewBag.QtEstoque, @readonly = "readonly", @value = "1" } })
                        <input type="button" value="+" id="btn-sum" onclick="somaQtd()" />
                    </p>
                    <br />
                    <p>
                        Calcular frete: &nbsp; <input type="text" class="inp-calc-frete" placeholder="CEP" name="no_cep" id="no_cep" maxlength="9" onblur="calcFrete(this.value);"/>
                    </p>
                    <p id="txt_frete" style="display: none;">
                        <input type="text" id="resp_frete" disabled/>
                    </p>
                    <br />
                    <input type="submit" value="Adcionar ao Carrinho" class="btn-add" />

                }
                else
                {
                    <p class="text-danger">Produto fora de estoque</p>
                }


                <br><br>


            </div>

        </div>
    </div>



}

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#no_cep").inputmask("mask", { "mask": "99999-999" }, { reverse: true });

        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

PythonGames/PythonGames/Views/Carrinho/ConfirmarCompra.cshtml
@model PythonGames.Classes.Models.Entrega

@{
    ViewBag.Title = "Confirmar Compra";
}

<script>

    function frete(cep) {
        $.ajax({
            url: '@Url.Action("CalculaFrete","Carrinho")?cep='+cep,
            type: "POST",
            contentType: "aplication/json",
            data: "",
            success: function (result) {
                document.getElementById('dt_entrega').value = (result[0]+" dias");
                document.getElementById('vl_frete').value = (result[1]+"R$");
            },
            error: function (xhr, exception) {
                alert("Erro ao calcular frete");
                document.getElementById('dt_entrega').value = ("");
                document.getElementById('vl_frete').value = ("");
            }
        });
    }

    function limpa_formulário_cep() {
        //Limpa valores do formulário de cep.
        document.getElementById('nm_rua').value = ("");
        document.getElementById('nm_bairro').value = ("");
        document.getElementById('nm_cidade').value = ("");
        document.getElementById('nm_estado').value = ("");
        document.getElementById('dt_entrega').value = ("");
        document.getElementById('vl_frete').value = ("");
    }

    function meu_callback(conteudo) {
        if (!("erro" in conteudo)) {
            //Atualiza os campos com os valores.
            document.getElementById('nm_rua').value = (conteudo.logradouro);
            document.getElementById('nm_bairro').value = (conteudo.bairro);
            document.getElementById('nm_cidade').value = (conteudo.localidade);
            document.getElementById('nm_estado').value = (conteudo.uf);
        } //end if.
        else {
            //CEP não Encontrado.
            limpa_formulário_cep();
            alert("CEP não encontrado.");
        }
    }

    function pesquisacep(valor) {

        //Nova variável "cep" somente com dígitos.
        var cep = valor.replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {

            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{8}$/;

            //Valida o formato do CEP.
            if (validacep.test(cep)) {

                //Preenche os campos com "..." enquanto consulta webservice.
                document.getElementById('nm_estado').value = "...";
                document.getElementById('nm_bairro').value = "...";
                document.getElementById('nm_cidade').value = "...";
                document.getElementById('nm_rua').value = "...";
                document.getElementById('dt_entrega').value = "...";
                document.getElementById('vl_frete').value = "...";

                //Cria um elemento javascript.
                var script = document.createElement('script');

                //Sincroniza com o callback.
                script.src = 'https://viacep.com.br/ws/' + cep + '/json/?callback=meu_callback';

                //Insere script no documento e carrega o conteúdo.
                document.body.appendChild(script);

                //Chamando método para calcular frete
                frete(cep);


            } //fim if.
            else {
                //cep é inválido.
                limpa_formulário_cep();
                alert("Formato de CEP inválido.");
            }
        } //fim if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulário_cep();
        }
    }
</script>








<h2 class="titulo-form">Confirmar Compra</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <br />
    <h4 class="text-center">Entrega</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="div-form-col1">

        <div class="">
            @Html.LabelFor(model => model.no_cep, htmlAttributes: new { @class = "" })
            <div class="">
                @Html.EditorFor(model => model.no_cep, new { htmlAttributes = new { @id = "no_cep", onblur = "pesquisacep(this.value);" } })<br />
                @Html.ValidationMessageFor(model => model.no_cep, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="">
            @Html.LabelFor(model => model.nm_estado, htmlAttributes: new { @class = "" })
            <div class="">
                @Html.EditorFor(model => model.nm_estado, new { htmlAttributes = new { @readonly = "readonly", @id = "nm_estado" } })
            </div>
        </div>

        <div class="">
            @Html.LabelFor(model => model.nm_cidade, htmlAttributes: new { @class = "" })
            <div class="">
                @Html.EditorFor(model => model.nm_cidade, new { htmlAttributes = new { @readonly = "readonly", @id = "nm_cidade" } })
            </div>
        </div>

        <div class="">
            @Html.LabelFor(model => model.nm_bairro, htmlAttributes: new { @class = "" })
            <div class="">
                @Html.EditorFor(model => model.nm_bairro, new { htmlAttributes = new { @readonly = "readonly", @id = "nm_bairro" } })
            </div>
        </div>

        <div class="">
            @Html.LabelFor(model => model.nm_rua, htmlAttributes: new { @class = "" })
            <div class="">
                @Html.EditorFor(model => model.nm_rua, new { htmlAttributes = new { @readonly = "readonly", @id = "nm_rua" } })
            </div>
        </div>

    </div>


    <div class="div-form-col2">

        <div class="">
            @Html.LabelFor(model => model.no_end, htmlAttributes: new { @class = "" })
            <div class="">
                @Html.EditorFor(model => model.no_end, new { htmlAttributes = new { @class = "" } })<br />
                @Html.ValidationMessageFor(model => model.no_end, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="">
            @Html.LabelFor(model => model.nm_complemento, htmlAttributes: new { @class = "" })
            <div class="">
                @Html.EditorFor(model => model.nm_complemento, new { htmlAttributes = new { @class = "" } })
                @Html.ValidationMessageFor(model => model.nm_complemento, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="">
            @Html.LabelFor(model => model.vl_frete, htmlAttributes: new { @class = "" })
            <div class="">
                <input class="text-box single-line" data-val="true" id="vl_frete" name="vl_frete" readonly="readonly" type="text" />
            </div>
        </div>

        <div class="">
            <label class="" for="dt_entrega">Prazo de Entrega</label>
            <div class="">
                <input class="text-box single-line" data-val="true" id="dt_entrega" name="dt_entrega" readonly="readonly" />
            </div>
        </div>

    </div>
    <br />
    <br />
    <h4 class="text-center">Pagamento</h4>
    <hr />
    <div class="div-form-col1">
        @Html.DropDownList("cd_forma", new SelectList(ViewBag.Formas, "cd_forma", "nm_forma", "Selecione"),
        htmlAttributes: new { @class = "standardSelect" }) <br /><br />

        <label class="" for="nm_cartao"> Nome no Cartão </label><br />
        <input type="text" maxlength="50" required name="nm_cartao" id="nm_cartao" /><br />

        <label class="" for="no_cartao"> Número do Cartão </label><br />
        <input type="text" maxlength="19" required name="no_cartao" id="no_cartao" /><br />
    </div>
    <div class="div-form-col2">
        <label class="" for="no_cvv"> CVV </label><br />
        <input type="text" maxlength="3" required name="no_cvv" id="no_cvv" /><br />

        <label class="" for="dt_validade"> Data de validade </label><br />
        <input type="date" required name="dt_validade" id="dt_validade" /><br />
    </div>

    <div class="">
        <div class="btn-form">
            <p class="text-danger">
                @ViewBag.ErroMsg
            </p>
            <p>
                @Html.ValidationMessageFor(model => model.nm_estado, "", new { @class = "text-danger" })
            </p>
            <input type="submit" value="Finalizar" class="btn btn-orange" />
        </div>
    </div>
</div>
}

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#no_cep").inputmask("mask", { "mask": "99999-999" }, { reverse: true });
            $("#no_cartao").inputmask("mask", { "mask": "9999-9999-9999-9999" }, { reverse: true });
            $("#no_cvv").inputmask("mask", { "mask": "999" }, { reverse: true });
        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

PythonGames/PythonGames/Views/Carrinho/Index.cshtml
@model IEnumerable<PythonGames.Classes.Models.ItensCarrinho>
<link href="~/Content/EstiloProdutos.css" rel="stylesheet" />
@{
    ViewBag.Title = "Meu Carrinho";
}

<h2 class="titulo-form">Meu Carrinho</h2>
@if (Model.Count() == 0)
{
    <br />
    <h5 class="text-center">Ainda não há itens no seu carrinho :(</h5>
    <br />
    <p class="text-center"> @Html.ActionLink("Adicione itens!!","Index","Home") </p>
}
@if (Model.Count() != 0)
{
    <ul class="prod-group">

        @foreach (var item in Model)
        {
            <li>
                <a href="~/Carrinho/AdicionarItem?cd=@Html.DisplayFor(modelItem => item.cd_produto)">
                    <div class="card-prod">
                        <div class="img-prod" style="background-image: url('@Html.DisplayFor(modelItem => item.link_img)');">
                        </div>
                        <h5 title="@Html.DisplayFor(modelItem => item.nm_prod)">
                            @Html.DisplayFor(modelItem => item.nm_prod)
                        </h5>
                        <p>@Html.DisplayFor(modelItem => item.nm_categoria)</p>
                        <p>Valor unitário: R$ @Html.DisplayFor(modelItem => item.vl_prod)</p>
                        <p>Quantidade: @Html.DisplayFor(modelItem => item.qt_item)</p>
                        <p>Valor total: R$ @Html.DisplayFor(modelItem => item.vl_item)</p>

                        <br />
                        <br />

                        @Html.ActionLink("Remover", "RemoverItem", new { cd = item.cd_produto }, new
                            {
                                @class = "btn-del",
                                onclick = "return confirm('Deseja realmente remover " +
                                @Html.DisplayFor(modelItem => item.nm_prod) + " do carrinho? ');"
                            })
                    </div>



                </a>
            </li>

        }

    </ul>
    <div class="btn-form">
        <p>
            <hr />
            Valor total do carrinho: @ViewBag.ValorCarrinho R$
            <br />
            <br />
            @Html.ActionLink("Confirmar Compra","ConfirmarCompra",null,new { @class = "btn-orange" })
            <br />
        </p>
    </div>
}