PythonGames/PythonGames/Areas/Gerenciamento/Controllers/SuporteController.cs
using PythonGames.Classes.DAOs;
using PythonGames.Classes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PythonGames.Areas.Gerenciamento.Controllers
{
    public class SuporteController : Controller
    {
        CarrinhoDAO carDAO = new CarrinhoDAO();
        ItensCarrinhoDAO icDAO = new ItensCarrinhoDAO();
        SuporteDAO supDAO = new SuporteDAO();
        // GET: Gerenciamento/Suporte
        public ActionResult Index()
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            return View(supDAO.Listar());
        }

        [HttpPost]
        public ActionResult Index(string cpf_cli)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            if (cpf_cli == "")
                cpf_cli = "___.___.___-__";
            return View(supDAO.ListarPorCpf(cpf_cli));
        }



        public ActionResult EscolherCarrinho()
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            return View(carDAO.Listar());
        }

        [HttpPost]
        public ActionResult EscolherCarrinho(string cpf_cli)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            if (cpf_cli == "")
                cpf_cli = "___.___.___-__";
            return View(carDAO.ListarPorCpf(cpf_cli));
        }



        public ActionResult VendaEscolhida(int cd)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            return View(icDAO.Listar(cd));
        }



        public ActionResult Cadastrar(int cd_produto, int cd_carrinho)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            Suporte suporte = new Suporte()
            {
                cd_carrinho = cd_carrinho,
                cd_produto = cd_produto
            };

            return View(suporte);
        }

        [HttpPost]
        public ActionResult Cadastrar(Suporte sup)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    supDAO.Insert(sup);
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.ErroMsg = "Algo Deu Errado :(";
                    return View();
                }
            }
            else
                return View();
        }



        public ActionResult Detalhes(int cd)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            Suporte sup = supDAO.ListarPorCd(cd);
            ViewBag.Cd = cd;
            ViewBag.Status = sup.sup_status;

            return View(sup);
        }



        public ActionResult AlterarStatus(int cd)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            supDAO.UpdateStatus(cd);
            return RedirectToAction("Detalhes", new { cd = cd });
        }



        public ActionResult Alterar(int cd)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            if((int)Session["AcFuncionarioLogado"] != 1)
                return RedirectToAction("Index");

            Suporte sup = supDAO.ListarPorCd(cd);
            ViewBag.Cd = cd;

            return View(sup);
        }

        [HttpPost]
        public ActionResult Alterar(Suporte sup)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    supDAO.Update(sup);
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.ErroMsg = "Algo Deu Errado :(";
                    return View();
                }
            }
            else
            {
                return View();
            }
        }



        public ActionResult Deletar(int cd)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            if ((int)Session["AcFuncionarioLogado"] != 1)
                return RedirectToAction("Index");

            supDAO.Delete(cd);

            return RedirectToAction("Index");
        }
    }
}

PythonGames/PythonGames/Areas/Gerenciamento/Controllers/VendaController.cs
using PythonGames.Classes;
using PythonGames.Classes.DAOs;
using PythonGames.Classes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PythonGames.Areas.Gerenciamento.Controllers
{
    public class VendaController : Controller
    {
        CarrinhoDAO carDAO = new CarrinhoDAO();
        CartaoDAO cartaoDAO = new CartaoDAO();
        ClienteDAO cliDAO = new ClienteDAO();
        FormaDePagamentoDAO frmDAO = new FormaDePagamentoDAO();
        ItensCarrinhoDAO icDAO = new ItensCarrinhoDAO();
        ProdutoDAO prodDAO = new ProdutoDAO();
        // GET: Gerenciamento/Venda
        public ActionResult Index()
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            Session["CarrinhoGerenciamento"] = null;
            Session["ItensCarrinhoGerenciamento"] = null;
            Session["CarrinhoNmCli"] = null;
            Session["CarrinhoNmCli"] = null;

            return View(carDAO.Listar());
        }

        [HttpPost]
        public ActionResult Index(string cpf_cli)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            if (cpf_cli == "")
                cpf_cli = "___.___.___-__";
            return View(carDAO.ListarPorCpf(cpf_cli));
        }



        public ActionResult Cadastrar()
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            ViewBag.Formas = frmDAO.ListarParaGerenciamento();

            Carrinho carrinho = new Carrinho();
            if (Session["CarrinhoCdCli"] != null)
                carrinho.cd_cliente = (int)Session["CarrinhoCdCli"];

            if (Session["CarrinhoNmCli"] != null)
                carrinho.nm_cli = (string)Session["CarrinhoNmCli"];

            return View(carrinho);
        }

        [HttpPost]
        public ActionResult Cadastrar(Carrinho carrinho)
        {
            if (ModelState.IsValid)
            {
                carrinho.cd_funcionario = (int)Session["CdFuncionarioLogado"];
                carrinho.vl_total = 0;
                carrinho.dt_venda = DateTime.Now;
                Session["CarrinhoGerenciamento"] = carrinho;

                Session["ItensCarrinhoGerenciamento"] = new List<ItensCarrinho>();

                return RedirectToAction("ItensCarrinho");
            }
            else
                return View();
        }



        public ActionResult ItensCarrinho()
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            if (Session["CarrinhoGerenciamento"] == null || Session["ItensCarrinhoGerenciamento"] == null)
                return RedirectToAction("Index");

            Carrinho carrinho = (Carrinho)Session["CarrinhoGerenciamento"];
            ViewBag.ValorCarrinho = carrinho.vl_total;
            ViewBag.FrmPag = carrinho.cd_forma;

            List<ItensCarrinho> lista = (List<ItensCarrinho>)Session["ItensCarrinhoGerenciamento"];
            return View(lista);
        }



        [HttpPost]
        public ActionResult ItensCarrinho(string nm_cartao, string no_cartao, string no_cvv)
        {
            List<ItensCarrinho> itens = (List<ItensCarrinho>)Session["ItensCarrinhoGerenciamento"];
            Carrinho carrinho = (Carrinho)Session["CarrinhoGerenciamento"];

            if (itens.Count == 0)
            {
                ViewBag.ErroMsg = "Não Há Itens Neste Carrinho";
                ViewBag.ValorCarrinho = carrinho.vl_total;
                ViewBag.FrmPag = carrinho.cd_forma;

                return View(itens);
            }

            Cartao cartao = new Cartao();
            if (carrinho.cd_forma != 3)
            {
                DateTime dt_validade = DateTime.Parse(Request["dt_validade"]);
                cartao = ChecaCartao(nm_cartao, no_cartao, no_cvv.Replace("_",string.Empty), dt_validade);
                if (cartao == null)
                {
                    ViewBag.ValorCarrinho = carrinho.vl_total;
                    ViewBag.FrmPag = carrinho.cd_forma;

                    return View(itens);
                }
            }

            try
            {
                int cd = carDAO.InsertGerenciamento(carrinho);
                foreach (ItensCarrinho item in itens)
                {
                    item.cd_carrinho = cd;
                    icDAO.Insert(item);
                }

                if (carrinho.cd_forma != 3)
                {
                    cartao.cd_carrinho = cd;
                    cartaoDAO.Insert(cartao);
                }

                Session["CarrinhoGerenciamento"] = null;
                Session["ItensCarrinhoGerenciamento"] = null;
            }
            catch
            {
                ViewBag.ErroMsg = "Algo Deu Errado :(";
                ViewBag.ValorCarrinho = carrinho.vl_total;
                ViewBag.FrmPag = carrinho.cd_forma;

                return View(itens);
            }

            return RedirectToAction("Index");
        }

        public Cartao ChecaCartao(string nm_cartao, string no_cartao, string no_cvv, DateTime dt_validade)
        {
            // validacoes cartao
            if(!Validacoes.ValidaCartao(no_cartao))
            {
                ViewBag.ErroMsg = "Número do Cartão inválido";
                return null;
            }
            if (DateTime.Now > dt_validade)
            {
                ViewBag.ErroMsg = "Data De Validade Do Cartão Inválida";
                return null;
            }
            if (no_cvv.Length != 3)
            {
                ViewBag.ErroMsg = "CVV Do Cartão Inválido";
                return null;
            }

            Cartao cartao = new Cartao();
            cartao.nm_cartao = nm_cartao;
            cartao.no_cartao = no_cartao;
            cartao.no_cvv = no_cvv;
            cartao.dt_validade = dt_validade;

            return cartao;
        }



        public ActionResult Detalhes(int cd)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            Carrinho carrinho = carDAO.ListarPorCd(cd);
            if (carrinho.cd_forma != 3)
            {
                string no_cartao = cartaoDAO.ListarPorCd(cd);
                ViewBag.NoCartao = no_cartao.Substring(no_cartao.Length-4); ;
            }

            return View(carrinho);
        }



        public ActionResult ItensVenda(int cd)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            ViewBag.Cd = cd;
            return View(icDAO.Listar(cd));
        }



        public ActionResult EscolherProduto()
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            if (Session["CarrinhoGerenciamento"] == null || Session["ItensCarrinhoGerenciamento"] == null)
                return RedirectToAction("Index");

            return View(prodDAO.Listar());
        }

        [HttpPost]
        public ActionResult EscolherProduto(string busca)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            if (Session["CarrinhoGerenciamento"] == null || Session["ItensCarrinhoGerenciamento"] == null)
                return RedirectToAction("Index");

            return View(prodDAO.ListarPorBusca(busca));
        }



        public ActionResult AdicionarItem(int cd)
        {
            if (Session["FuncionarioLogado"] == null)
                return RedirectToAction("Login", "Funcionario");

            if (Session["CarrinhoGerenciamento"] == null || Session["ItensCarrinhoGerenciamento"] == null)
                return RedirectToAction("Index");

            Produto prod = prodDAO.ListarPorCd(cd);
            ItensCarrinho item = new ItensCarrinho();

            item.cd_produto = prod.cd_produto;
            ViewBag.CdProduto = prod.cd_produto;
            ViewBag.NmProd = prod.nm_prod;
            ViewBag.LinkImg = prod.link_img;
            ViewBag.NmCat = prod.nm_categoria;
            ViewBag.VlProd = prod.vl_prod;
            ViewBag.QtEstoque = prod.qt_estoque;
            ViewBag.ProdDesc = prod.prod_desc;

            return View(item);
        }

        [HttpPost]
        public ActionResult AdicionarItem(ItensCarrinho item)
        {
            if (item.qt_item > 0)
            {
                List<ItensCarrinho> lista = (List<ItensCarrinho>)Session["ItensCarrinhoGerenciamento"];
                
                //deletando possivel existencia de outro item do mesmo produto
                var itemExclusao = lista.FirstOrDefault(i => i.cd_produto == item.cd_produto);
                lista.Remove(itemExclusao);

                Produto prod = prodDAO.ListarPorCd(item.cd_produto);

                item.cd_produto = prod.cd_produto;
                item.nm_prod = prod.nm_prod;
                item.link_img = prod.link_img;
                item.nm_categoria = prod.nm_categoria;
                item.vl_prod = prod.vl_prod;
                item.qt_estoque = prod.qt_estoque;
                item.prod_desc = prod.prod_desc;

                lista.Add(item);
                Session["ItensCarrinhoGerenciamento"] = lista;

                Carrinho carrinho = (Carrinho)Session["CarrinhoGerenciamento"];
                carrinho.vl_total = 0;
                foreach (ItensCarrinho ic in lista)
                {
                    carrinho.vl_total += ic.vl_item;
                }
                Session["CarrinhoGerenciamento"] = carrinho;

                return RedirectToAction("ItensCarrinho");
            }
            else

PythonGames/PythonGames/Areas/Gerenciamento/Views/Suporte/Alterar.cshtml
@model PythonGames.Classes.Models.Suporte

@{
    ViewBag.Title = "Alterar Suporte";
}

<h2 class="titulo-form">Alterar Suporte</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Suporte</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div style="display:none;">
            <div class="form-group">
                @Html.LabelFor(model => model.cd_suporte, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.cd_suporte, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.cd_suporte, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.cd_produto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.cd_produto, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.cd_produto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.cd_carrinho, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.cd_carrinho, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.cd_carrinho, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="div-form-col1">
            <div class="">
                @Html.LabelFor(model => model.sup_descricao, htmlAttributes: new { @class = "" })
                <div class="">
                    @Html.TextAreaFor(model => model.sup_descricao, new { htmlAttributes = new { @class = "" } }) <br />
                    @Html.ValidationMessageFor(model => model.sup_descricao, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="div-form-col1">
            <div class="">
                @Html.LabelFor(model => model.dt_sup, htmlAttributes: new { @class = "" })
                <div class="">
                    @Html.EditorFor(model => model.dt_sup, new { htmlAttributes = new { @type = "date" } }) <br />
                    @Html.ValidationMessageFor(model => model.dt_sup, "", new { @class = "text-danger" })
                    <br />
                    <br />
                </div>
            </div>
        </div>


        <div class="">
            <div class="btn-form">
                <p class="text-danger">
                    @ViewBag.ErroMsg
                </p>
                <input type="submit" value="Salvar Alterações" class="btn btn-orange" />
            </div>
        </div>
    </div>
}

<br />
<div class="link-voltar-form">
    <i class="fas fa-arrow-circle-left">
        @Html.ActionLink("Voltar", "Detalhes",new { cd = @ViewBag.Cd} )
    </i>
</div>

PythonGames/PythonGames/Areas/Gerenciamento/Views/Suporte/Cadastrar.cshtml
@model PythonGames.Classes.Models.Suporte

@{
    ViewBag.Title = "Cadastrar Suporte";
}

<h2 class="titulo-form">Cadastrar Suporte</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Suporte</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div style="display:none;">
            <div class="form-group">
                @Html.LabelFor(model => model.cd_produto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.cd_produto, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.cd_produto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.cd_carrinho, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.cd_carrinho, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.cd_carrinho, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="div-form-col1">
            <div class="">
                @Html.LabelFor(model => model.sup_descricao, htmlAttributes: new { @class = "" })
                <div class="">
                    @Html.TextAreaFor(model => model.sup_descricao, new { htmlAttributes = new { @class = "" } }) <br />
                    @Html.ValidationMessageFor(model => model.sup_descricao, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="div-form-col1">
            <div class="">
                @Html.LabelFor(model => model.dt_sup, htmlAttributes: new { @class = "" })
                <div class="">
                    @Html.EditorFor(model => model.dt_sup, new { htmlAttributes = new { @type = "date" } }) <br />
                    @Html.ValidationMessageFor(model => model.dt_sup, "", new { @class = "text-danger" })
                    <br />
                    <br />
                </div>
            </div>
        </div>


        <div class="">
            <div class="btn-form">
                <p class="text-danger">
                    @ViewBag.ErroMsg
                </p>
                <input type="submit" value="Cadastrar" class="btn btn-orange" />
            </div>
        </div>
    </div>
}

<br />
<div class="link-voltar-form">
    <i class="fas fa-arrow-circle-left">
        @Html.ActionLink("Voltar", "Index")
    </i>
</div>

PythonGames/PythonGames/Areas/Gerenciamento/Views/Suporte/Detalhes.cshtml
@model PythonGames.Classes.Models.Suporte

@{
    ViewBag.Title = "Detalhes de Suporte";
}

<h2 class="titulo-form">Detalhes de Suporte</h2>
<br />
<div>
    <div class="form-carrinho">

        <div class="item-form-carrinho form-carrinho-img" style="background-image: url('@Html.DisplayFor(model => model.link_img)');">
        </div>
        <div class="item-form-carrinho form-carrinho-inputs">
            <h3>@Html.DisplayFor(model => model.nm_prod)</h3>
            <hr style="border: 1px solid rgb(255, 127, 38);">

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.cd_carrinho)
                </span>
                @Html.DisplayFor(model => model.cd_carrinho)
            </p>

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.dt_sup)
                </span>
                @Html.DisplayFor(model => model.dt_sup)
            </p>

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.sup_descricao)
                </span>
                @Html.DisplayFor(model => model.sup_descricao)
            </p>

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.sup_status)
                </span>
                @if (@ViewBag.Status == 0)
                {
                    <span class="text-danger fas fa-times-circle" title="Alterar Status de Suporte">  
                        @Html.ActionLink("Não Atendido", "AlterarStatus", new { cd = @ViewBag.Cd }, new
                        {
                            @class = "text-danger",
                            onclick = "return confirm('Deseja realmente alterar o status deste suporte?? ');"
                        })
                    </span>
                }
                else
                {
                    <span style="font-weight: normal;" class="fas fa-check-circle text-success">Atendido</span>
                }
            </p>

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.cpf_cli)
                </span>
                @Html.DisplayFor(model => model.cpf_cli)
            </p>

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.nm_cli)
                </span>
                @Html.DisplayFor(model => model.nm_cli)
            </p>

            <p>
                <span style="font-weight: bold;">
                    @Html.DisplayNameFor(model => model.nm_email)
                </span>
                @Html.DisplayFor(model => model.nm_email)
            </p>

            @if ((int)Session["AcFuncionarioLogado"] == 1)
            {
                <br />
                @Html.ActionLink("Alterar", "Alterar", new { cd = @ViewBag.Cd }, new { @class = "btn-alt" })
                @Html.ActionLink("Deletar", "Deletar", new { cd = @ViewBag.Cd }, new
                {
                    @class = "btn-del",
                    onclick = "return confirm('Deseja realmente deletar este suporte?? ');"
                })
            }


        </div>
    </div>
</div>
<br />
<div class="link-voltar-form">
    <i class="fas fa-arrow-circle-left">
        @Html.ActionLink("Voltar", "Index")
    </i>
</div>

PythonGames/PythonGames/Areas/Gerenciamento/Views/Suporte/EscolherCarrinho.cshtml
@model IEnumerable<PythonGames.Classes.Models.Carrinho>

@{
    ViewBag.Title = "Escolher Venda";
}

<h2>Escolher Venda</h2>
<br />

<div class="navbar">
    <form class="form-inline" method="post">
        <input class="form-control mr-sm-2" id="cpf_cli" name="cpf_cli" type="search" placeholder="Buscar por CPF">
        <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Buscar</button>
    </form>
</div>

<br />
<table class="table table-borderless text-center">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.cd_carrinho)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nm_cli)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dt_venda)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vl_total)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="user-select: none;">
                @Html.DisplayFor(modelItem => item.cd_carrinho)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nm_cli)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dt_venda)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.vl_total) R$
            </td>
            <td>
                @Html.ActionLink("Escolher", "VendaEscolhida", new { cd = item.cd_carrinho })
            </td>
        </tr>
    }

</table>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#cpf_cli").inputmask("mask", { "mask": "999.999.999-99" }, { reverse: true });
        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

PythonGames/PythonGames/Areas/Gerenciamento/Views/Suporte/Index.cshtml
@model IEnumerable<PythonGames.Classes.Models.Suporte>

@{
    ViewBag.Title = "Lista de Suportes";
}

<h2>Lista de Suportes</h2>
<br />

<div class="navbar">
    @Html.ActionLink("Novo Suporte", "EscolherCarrinho", null, new { @class = "btn-orange" })

    <form class="form-inline" method="post">
        <input class="form-control mr-sm-2" id="cpf_cli" name="cpf_cli" type="search" placeholder="Buscar por CPF">
        <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Buscar</button>
    </form>
</div>

<br />
<table class="table table-borderless text-center">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.cd_carrinho)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nm_cli)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nm_prod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dt_sup)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sup_status)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td title="Ver detalhes da venda">
                @Html.ActionLink(item.cd_carrinho + "", "Detalhes", "Venda", new { cd = item.cd_carrinho }, new { })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nm_cli)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nm_prod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dt_sup)
            </td>
            <td>
                @if (item.sup_status == 0)
                {
                    <p class="text-danger fas fa-times-circle" title="Alterar Status de Suporte">
                        @Html.ActionLink("Não Atendido", "AlterarStatus", new { cd = item.cd_suporte }, new
                        {
                        @class = "text-danger",
                        onclick = "return confirm('Deseja realmente alterar o status deste suporte?? ');"
                        })
                    </p>
                }
                else
                {
                    <p class="fas fa-check-circle text-success"> Atendido</p>
                }
            </td>
            <td>
                @Html.ActionLink("Ver Detalhes", "Detalhes", new { cd = item.cd_suporte })
            </td>
        </tr>
    }

</table>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#cpf_cli").inputmask("mask", { "mask": "999.999.999-99" }, { reverse: true });
        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

PythonGames/PythonGames/Areas/Gerenciamento/Views/Suporte/VendaEscolhida.cshtml
@model IEnumerable<PythonGames.Classes.Models.ItensCarrinho>
<link href="~/Content/EstiloProdutos.css" rel="stylesheet" />
@{
    ViewBag.Title = "Escolher Produto";
}

<h2>Escolha o Produto</h2>


<ul class="prod-group">

    @foreach (var item in Model)
    {
        <li>

            <div class="card-prod">
                <div class="img-prod" style="background-image: url('@Html.DisplayFor(modelItem => item.link_img)');">
                </div>
                <h5 title="@Html.DisplayFor(modelItem => item.nm_prod)">
                    @Html.DisplayFor(modelItem => item.nm_prod)
                </h5>
                <p>@Html.DisplayFor(modelItem => item.nm_categoria)</p>
                <p>R$ @Html.DisplayFor(modelItem => item.vl_prod)</p>

                <br />

            </div>
            <div class="add-link">
                @Html.ActionLink("+", "Cadastrar", new { cd_produto = item.cd_produto, cd_carrinho = item.cd_carrinho })
            </div>



        </li>
    }

</ul>